FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Komuto

Polls is a simple API allowing consumers to view polls and vote in them.

## Authentication [/users/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "admin@komuto.com",
            "password": "admin"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "User Data",
            "data": {
                "email_users": "admin@komuto.com",
                "id_users": 66,
                "id_marketplaceuser": 0,
                "namalengkap_users": "Admin Komuto",
                "no_anggotakoperasi_users": null,
                "approval_koperasi_users": "0",
                "pathfoto_users": null,
                "nohp_users": null,
                "tgl_create_users": "2017-06-01T17:00:00.000Z",
                "tgl_join_koperasi": null,
                "jeniskelamin_users": null,
                "status_users": "1",
                "tglstatus_users": "2017-05-01T20:01:28.000Z",
                "ibukandung_users": null,
                "auth_key": null,
                "kota_lahir": null,
                "tgl_lahir": null,
                "saldo_wallet": null,
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTY2MjM2MTJ9.flFtOxurZF_wU15OPoPkjBzqe7mn__7jPUYcLTglMe0"
            }
        }

## User Collection [/users]

### Registration [POST]

+ Request (application/json)

        {
            
        }

+ Response 201 (application/json)

        {
                "code": 200,
                "status": true,
                "message": "User Data",
                "data": {}
        }

### Get User [GET /users/{?user_id}]

+ Request
    + Parameters
        + id_users: 66 (required, number)

    + Headers

            Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTY2MjM2MTJ9.flFtOxurZF_wU15OPoPkjBzqe7mn__7jPUYcLTglMe0



+ Response 200 (application/json)

        {
              "code": 200,
              "status": true,
              "message": "User Data",
              "data": {
                "id_users": 66,
                "id_marketplaceuser": 0,
                "email_users": "admin@komuto.com",
                "namalengkap_users": "Admin Komuto",
                "no_anggotakoperasi_users": null,
                "approval_koperasi_users": "0",
                "pathfoto_users": null,
                "nohp_users": null,
                "tgl_create_users": 1496336400,
                "tgl_join_koperasi": null,
                "jeniskelamin_users": null,
                "status_users": "1",
                "tglstatus_users": 1493668888,
                "ibukandung_users": null,
                "auth_key": null,
                "kota_lahir": null,
                "tgl_lahir": null,
                "saldo_wallet": null
              }
        }

### User Activation [POST /users/{?user_id}/activate]

+ Request (application/json)

+ Response 200 (application/json)

        {
                "code": 200,
                "status": true,
                "message": "User Data"
                "data": {}
        }

### Change Status [POST /users/{?user_id}/status]

+ Parameters
    +   user_id: 2 (number, required)

+ Response 200 (application/json)

        {
                "code": 200,
                "status": true,
                "message": "User Data",
                "data": {}
        }

## Marketplace Collection [/marketplace]

### Get Term of Service [GET /marketplace/{?marketplace_id}/term]

+ Parameters 
    + marketplace_id: 55 (required, number)
    
+ Response 200 (application/json)

        {
                "code": 200,
                "status": true,
                "message": "Marketplace Data",
                "data": {}
        }
        
### Get Privacy Policy [GET /marketplace/{?marketplace_id}/policy]

+ Parameters
    + marketplace_id: 99 (required, number)

+ Response 200 (application/json)

        {
                "code": 200,
                "status": true,
                "message": "Marketplace Data",
                "data": {}
        }